{{- if .Values.extSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.MongoDBCommunity.name }}
  namespace: {{ .Values.MongoDBCommunity.namespace }}
spec:
  provider:
    aws:
      region: {{ .Values.extSecrets.awsRegion }}
      service: {{ .Values.extSecrets.awsService }}
{{- range .Values.MongoDBCommunity.users }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.MongoDBCommunity.name }}-user-{{ .name }}"
  namespace: {{ $.Values.MongoDBCommunity.namespace }}
spec: 
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .passwordSecretRef.awsSecretPath }}
  refreshInterval: 3m
  secretStoreRef:
    kind: SecretStore
    name: {{ $.Values.MongoDBCommunity.name }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: "{{ .passwordSecretRef.name }}"
{{- end }}
{{- if .Values.MongoDBCommunity.monitoring.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.MongoDBCommunity.name }}-monitoring-{{ $.Values.MongoDBCommunity.monitoring.username }}"
  namespace: {{ $.Values.MongoDBCommunity.namespace }}
spec: 
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $.Values.extSecrets.awsSecretPathMonitoringCreds }}
  refreshInterval: 3m
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.MongoDBCommunity.name }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: "{{ .Values.extSecrets.monitoringCredsName }}"
{{- end }}
{{- if .Values.MongoDBCommunity.imagePullSecret }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.MongoDBCommunity.name }}-dockerhub"
  namespace: {{ $.Values.MongoDBCommunity.namespace }}
spec: 
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $.Values.extSecrets.awsSecretPathDockerCreds }}
  refreshInterval: 3m
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.MongoDBCommunity.name }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: "{{ .Values.extSecrets.DockerCreds }}"
{{- end }}
{{- end }}
