---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.MongoDBCommunity.name }}
  namespace: {{ .Values.MongoDBCommunity.namespace }} 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.MongoDBCommunity.name }}
  namespace: {{ .Values.MongoDBCommunity.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.MongoDBCommunity.name }}
  namespace:  {{ .Values.MongoDBCommunity.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.MongoDBCommunity.name }}
roleRef:
  kind: Role
  name: {{ .Values.MongoDBCommunity.name }}
  apiGroup: rbac.authorization.k8s.io
