stages:
  - lint
  - upload
  
helm_template_check:
  stage: lint
  image: 
    name: alpine/helm:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    - |
      for chart in charts/*; do
        if [ -d "$chart" ]; then  
          echo "Linting and templating $chart..."
          helm dependency build "$chart"
          helm lint "$chart" 
          helm template "$chart" --values "$chart/values.yaml" --namespace default  
        fi
      done
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - charts/**/*  

upload:
  image: 
    name: alpine/helm:latest
    entrypoint: ["/bin/sh", "-c"]
  stage: upload
  script:
    - helm package --dependency-update charts/*
    - helm package charts/*
    - curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@${CI_COMMIT_TAG}.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/${CI_PROJECT_NAME}/charts"
  only:
     - tags
