# Global values
image:
  repository: busybox
  tag: latest



# CronJob specific values
cronjob:
# If true, create cron jobs
  enabled: true
  spec:
    printenv:
      command: ["printenv"]
      args: ["HOSTNAME","PATH"]
      schedule: "* * * * *"

secretsExternal:
  NATS_ADDR: "/global/nats/addr"

# Job specific values
job:
  enabled: true
  spec:
    my-pre-install-job:
      backoffLimit: 5
      command:
        - "/bin/sh"
        - "-c"
      args:
        - "echo 'Hello from Job!'"

## Worker specific values
worker:
  enabled: true
  spec:
    my-worker:
      replicas: 2
      command:
        - "/bin/sh"
        - "-c"
      args:
        - "echo 'Hello from Worker!'"

