{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.secretName | default "otel-certs" }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.secretName | default "otel-certs" }}
    creationPolicy: Owner
  data:
  {{- range $key, $value := .Values.certs }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $value }}
  {{- end }}      
{{- end }}