MongoDBCommunity:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: mongo-database-k8app
  namespace: databases
  members: 3
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: mongoroot
      db: admin
      passwordSecretRef:
        awsSecretPath: /path/to/ssm/or/secret/.../mongo/password
        name: mongoroot
        key: mongoroot
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: mongoroot-scram
    - name: app
      db: admin
      passwordSecretRef:
        awsSecretPath: /path/to/ssm/or/secret/.../mongo/password
        name: app
        key: app
      roles:
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: app-scram
  additionalMongodConfig:
    journalCompressor: zlib
  monitoring:
    enabled: true
    username: monitoring
  tolerations: {}
  nodeSelector: {}
  resources: []
  affinity:
    podAffinityRequired: false
  storage:
    name: data-volume
    size: 10Gi
  readinessProbe:
    failureThreshold: 60
    initialDelaySeconds: 30
  pdb:
    minAvailable: 2
extSecrets:
  enabled: true
  awsRegion: eu-central-1
  awsService: SecretsManager #ParameterStore
  awsSecretPathMonitoringCreds: poc/monitoring-secret
  monitoringCredsName: metrics-endpoint-password
  monitoringCredsKey: password
