---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ template "clickhouse-access-secret.name" . }}
spec:
  provider:
    aws:
      region: {{ .Values.region }}
      service: SecretsManager
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "clickhouse-access-secret.name" . }}
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.clickhouseServer.awsSecretManagerPath }}
  refreshInterval: 3m
  secretStoreRef:
    kind: SecretStore
    name: {{ template "clickhouse-access-secret.name" . }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ template "clickhouse-access-secret.name" . }}