---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: clickhouse-user-access-{{ $.Release.Namespace }}
spec:
  provider:
    aws:
      region: {{ .Values.region }}
      service: {{ .Values.clickhouseServer.externalSecretService }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clickhouse-user-access-{{ $.Release.Namespace }}
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.clickhouseServer.externalSecretPath }}
  refreshInterval: 3m
  secretStoreRef:
    kind: SecretStore
    name: clickhouse-user-access-{{ $.Release.Namespace }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: clickhouse-user-access-{{ $.Release.Namespace }}