{{- if .Values.imagePullSecret.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ template "dockerhub-secret.name" . }}
spec:
  provider:
    aws:
      region: {{ .Values.region }}
      service: {{ .Values.clickhouseServer.externalSecretService }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "dockerhub-secret.name" . }}
spec:
  refreshInterval: 3m
  secretStoreRef:
    name: {{ template "dockerhub-secret.name" . }}
    kind: SecretStore
  target:
    name: {{ template "dockerhub-secret.name" . }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ template "dockerhub-secret.name" . }}
        property: .dockerconfigjson

{{- end }}