{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
provisioner: ebs.csi.aws.com
parameters:
  encrypted: "{{ .Values.storageClass.encrypted }}"
  fsType: {{ .Values.storageClass.fsType }}
  iops: "{{ .Values.storageClass.iops }}"
  throughput: "{{ .Values.storageClass.throughput }}"
  type: {{ .Values.storageClass.type }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
allowVolumeExpansion: true
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
{{- end }}