{{- if .Values.secretsExternal}}
{{- $appname := printf "%s" (include "name" .) -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $appname }}-external-secrets-ssm
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-7"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: {{ $appname }}-external-secrets-ssm
    creationPolicy: Owner
  data:
  {{- range $key, $value := .Values.secretsExternal}}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $value }}
  {{- end }}      
{{- end }}