{{- if .Values.volume.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  annotations:
   {{- if .Values.job.mountVolume }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    {{- else }}
    { }
    {{- end }}
  labels:
    app: {{template "name" . }}
    appver: "{{ .Values.image.tag }}"
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{ .Release.Name }}"

  name: {{ template "persistantClaim" .}}
spec:
  accessModes:
    {{ toYaml  .Values.volume.accessModes }}
  storageClassName: {{ template "storageClass" . }}
  resources:
    requests:
      storage: {{default "1Gi" .Values.volume.resources.requests.storage}}
{{- end -}}