{{- if .Values.volume.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-7"
  labels:
    app: {{template "name" . }}
    appver: "{{ .Values.image.tag }}"
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{ .Release.Name }}"
  name: {{ template "persistantClaim" .}}
spec:
  accessModes:
    {{ toYaml  .Values.volume.accessModes }}
  storageClassName: {{ template "storageClass" . }}
  resources:
    requests:
      storage: {{default "1Gi" .Values.volume.resources.requests.storage}}
{{- end -}}