{{- $appname := printf "%s" (include "name" .) -}}
{{- range $key, $value := .Values.secrets_files }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $appname }}-{{ $key }}-aws-secret
  namespace: {{ $.Release.Namespace }}
  annotations:
    checksum/secrets: {{ printf "%v" $.Values.secrets | sha256sum }}
{{/*    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}*/}}
    image/tag: "{{ $.Values.image.tag}}"
  labels:
    helm.sh/chart: "{{ $.Chart.Name}}-{{ $.Chart.Version}}"
    app: {{ $appname }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
spec:
  provider: aws
  secretObjects: # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - secretName: {{ $appname }}-{{ $key }}-file
      type: Opaque
      data:
        - objectName: {{ $key | quote}}
          key: {{ $key | quote }}
  parameters:
    objects: |
      - objectName: {{ $value | quote }}
        objectAlias: {{ $key }}
        objectType: "ssmparameter"
{{- end }}