{{- if .Values.secrets}}
{{- $appname := printf "%s" (include "name" .) -}}
{{- $uniqueSecrets := include "uniqueSecrets" . | fromJson -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $appname }}-aws-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    checksum/secrets: {{ printf "%v" .Values.secrets | sha256sum }}
    image/tag: "{{.Values.image.tag}}"
    helm.sh/hook: 'pre-install,pre-upgrade'
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: '-3'
  labels:
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  provider: aws
  secretObjects:
    - secretName: {{ $appname }}
      type: Opaque
      data:
        {{- range $envVar, $secretInfo := $uniqueSecrets }}
        {{- if eq $envVar $secretInfo.key }}
        - objectName: {{ $envVar | quote }}
          key: {{ $envVar | quote }}
        {{- end }}
        {{- end }}
  parameters:
    objects: |
      {{- range $envVar, $secretInfo := $uniqueSecrets }}
      {{- if eq $envVar $secretInfo.key }}
      - objectName: {{ $secretInfo.path | quote }}
        objectAlias: {{ $envVar | quote }}
        objectType: "ssmparameter"
      {{- end }}
      {{- end }}
{{- end -}}