{{- if .Values.secrets}}
{{- $appname := printf "%s" (include "name" .) -}}
{{- $uniqueSecrets := include "uniqueSecrets" . | fromJson -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $appname }}-aws-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    checksum/secrets: {{ printf "%v" .Values.secrets | sha256sum }}
    image/tag: "{{.Values.image.tag}}"
spec:
  provider: aws
  secretObjects:
    - secretName: {{ $appname }}
      type: Opaque
      data:
        {{- range $key, $_ := $uniqueSecrets }}
        - objectName: {{ $key | quote }}
          key: {{ $key | quote }}
        {{- end }}
  parameters:
    objects: |
      {{- range $envVar, $secretInfo := $uniqueSecrets }}
      {{- if eq $envVar $secretInfo.key }}
      - objectName: {{ $secretInfo.path | quote }}
        objectAlias: {{ $envVar | quote }}
        objectType: "ssmparameter"
      {{- end }}
      {{- end }}
{{- end -}}