storageClass: clickhouse-sc
region: eu-central-1

imagePullSecret:
  enabled: false
  name: "" #defined in _helpers.tpl

ingress:
  enabled: true
  name: "" #defined in _helpers.tpl
  ingressClass: nginx-external
  hostname: "" # NOTE: PLEASE SET VARIABLE. E.q.: clickhouse-abc.dosvc-40.pin-up.dev

clickhouseServer:
  image: clickhouse/clickhouse-server:24.6.2.17
  clusterName: "" # NOTE: PLEASE SET VARIABLE. E.q.: clickhouse-abc
  shardsCount: 1
  replicasCount: 2
  pdb:
    maxNumberPerNode: 1
  externalSecrets:
    service: ParameterStore #SecretsManager
    systemUsersSecret: "" #defined in _helpers.tpl
    systemUsersPath: "" # NOTE: PLEASE SET VARIABLE. E.q.: /poc/clickhouse-in-k8s/clickhouse-abc-system
    customUsersSecret: "" #defined in _helpers.tpl
    customUsersPath: "" # NOTE: PLEASE SET VARIABLE. E.q.: /poc/clickhouse-in-k8s/clickhouse-abc-custom

  volumes:
    dataVolume:
      size: 50Gi
    logVolume:
      size: 10Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 2Gi
      cpu: 2
  nodeSelector: {} # NOTE: PLEASE SET VARIABLE.
  tolerations: [] # NOTE: PLEASE SET VARIABLE.
  terminationGracePeriodSeconds: 120
  shutdownWaitUnfinished: 60
  settings:
    configMap:
      name: "" #defined in _helpers.tpl
      logRotationConfig: ~ # NOTE: PLEASE SET VARIABLE IF NEEDED.
      storageConfig: ~ # NOTE: PLEASE SET VARIABLE IF NEEDED.
      dictionaryConfig: ~ # NOTE: PLEASE SET VARIABLE IF NEEDED.

  systemUsers:
    admin:
      passwordFromSecret:
        key: admin_password
      profile: default
      quota: default
      networks:
        - 0.0.0.0/0
#    backup:
#      passwordFromSecret:
#        key: backup_password
#      profile: default
#      quota: default
#      networks:
#        - 0.0.0.0/0

  customUsers: {}

# NOTE: Access to specific DBs
#    user1:
#      passwordFromSecret:
#        key: user1_password
#      profile: default
#      quota: default
#      networks:
#        - 0.0.0.0/0
#      databases:
#        - db5
#        - system

# NOTE: Access to specific DBs and tables. Can't be used with `databases:` option.
#    user2:
#      passwordFromSecret:
#        key: user2_password
#      profile: default
#      quota: default
#      networks:
#        - 0.0.0.0/0
#      grants:
#        - GRANT INSERT ON db5.*
#        - GRANT SELECT ON system.zookeeper_connection

# NOTE: Access to all DBs
#    user3:
#      passwordFromSecret:
#        key: user3_password
#      profile: default
#      quota: default
#      networks:
#        - 0.0.0.0/0

  profiles:
    custom:
      readonly: "0"
      data_type_default_nullable: "1"
      insert_distributed_sync: "1"
      mutations_sync: "2"
      parallel_distributed_insert_select: "2"
      distributed_product_mode: allow
    readonly:
      readonly: "2"
      max_memory_usage: "20000000000"
      max_threads: "4"

  quotas:
    default:
      duration: "3600"
      errors: "0"
      execution_time: "0"
      queries: "0"
      read_rows: "0"
      result_rows: "0"
    custom:
      duration: "3600"
      errors: "0"
      execution_time: "900"
      queries: "3600"
      read_rows: "100000000"
      result_rows: "10000000"

backup:
  enabled: false # NOTE: PLEASE CHOOSE IF YOU PLAN TO HAVE BACKUPS
  clickhouseBackupServer:
    serviceAccount: "" #defined in _helpers.tpl
    backupBucket: "" # NOTE: PLEASE SET VARIABLE. E.q.: clickhouse-backup-tests-poc
    backupBucketRegion: eu-central-1
    backupBucketDebug: false
    logLevel: info
    backupIamRole: "" # NOTE: PLEASE SET VARIABLE. E.q.: arn:aws:iam::XXXXXXXXXXX:role/eks-devops-service-poc-dev-clickhouse-backup-iam-role
    backupImage: altinity/clickhouse-backup:2.5.27
    username: "backup"
    secretPasswordKey: "backup_password"
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Gi
        cpu: 200m
    watchInterval: "1h"
    fullInterval: "24h"
    keepLocal: "1"
    keepRemote: "24"
#    maxFileSize: "1073741824"
    allowEmptyBackups: true # NOTE: Need to be set as TRUE for first run Clickhouse Backup Server

clickhouseKeeper:
  clusterName: "" #defined in _helpers.tpl
  image: clickhouse/clickhouse-keeper:24.6.2.17
  replicasCount: 3
  volumes:
    dataVolume:
      size: 10Gi
    logVolume:
      size: 10Gi
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
  nodeSelector: {} # NOTE: PLEASE SET VARIABLE.
  tolerations: [] # NOTE: PLEASE SET VARIABLE.